version: '2'
services:
  testing-container-1:
    image: httpd:latest
    container_name: testing-1
    stdin_open: true
    tty: true
    volumes:
      - /root/docker/testing-container-1:/usr/local/apache2/htdocs
    restart: unless-stopped
    ports:
      - "9000:80"

  production-container-1:
    image: httpd:latest
    container_name: production-1
    stdin_open: true
    tty: true
    volumes:
      - /root/docker/production-container-1:/usr/local/apache2/htdocs
    restart: unless-stopped
    ports:
      - "9001:80"

  production-container-2:
    image: httpd:latest
    container_name: production-2
    stdin_open: true
    tty: true
    volumes:
      - /root/docker/production-container-2:/usr/local/apache2/htdocs
    restart: unless-stopped
    ports:
      - "9002:80"

  production-container-3:
    image: httpd:latest
    container_name: production-3
    stdin_open: true
    tty: true
    volumes:
      - /root/docker/production-container-3:/usr/local/apache2/htdocs
    restart: unless-stopped
    ports:
      - "9003:80"