---

- hosts: centos7
  user: root

  tasks:
    - name: Copy files to testing environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/dist/angular
        dest: /root/pipeline-storage/testing_1