---

- hosts: centos7
  user: root

  tasks:
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '771'
      become: yes

    - name: Transfer docker-compose.yml
      copy:
        src: /var/jenkins_home/workspace/angular-project/docker-compose.yml
        dest: /root/docker/docker-compose.yml

    - name: Run docker-compose.yml
      command: chdir=/root/docker docker-compose up -d

    - name: Transfer project files
      copy: 
        src: /var/jenkins_home/workspace/angular-project/angular/dist/angular/
        dest: /root/website

    - name: Deploy to testing environment
      command: echo /root/docker/testing-container-1 /root/docker/production-container-1 /root/docker/production-container-2 /root/docker/production-container-3 | xargs -n 1 cp /root/website/

