---

- hosts: centos8
  user: root

  tasks:
    - name: Copy files to testing environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/dist/angular
        des: /home/casper/pipeline-storage/testing_1