---

- hosts: centos7
  user: root

  tasks:

    - name: Update
      command: yum update -y
      become: yes

    - name: DOCKER add repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes

    - name: DOCKER enable docker repo
      ini_file:
        dest: /etc/yum.repos.d/docker-ce.repo
        section: 'docker-ce-edge'
        option: enabled
        value: 0
      become: yes

    - name: DOCKER install docker
      package:
        name: docker-ce
        state: latest
      become: yes

    - name: DOCKER enable docker
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: DOCKER install dependencies
      yum:
        name:
          - python3
          - python3-pip
          - python2-pip
        state: latest

    - name: DOCKER install python for docker
      command: pip install docker-py

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '771'
      become: yes

    - name: Transfer docker-compose.yml
      copy:
        src: /var/jenkins_home/workspace/angular-project/docker-compose.yml
        dest: /root/docker/docker-compose.yml

    - name: Run docker-compose.yml
      command: chdir=/root/docker docker-compose up -d

    - name: Deploy to testing environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/angular/dist/angular/
        dest: /root/docker/testing-container-1

    - name: Deploy to production environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/angular/dist/angular/
        dest: /root/docker/production-container-1

    - name: Deploy to production environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/angular/dist/angular/
        dest: /root/docker/production-container-2

    - name: Deploy to production environment
      copy: 
        src: /var/jenkins_home/workspace/angular-project/angular/dist/angular/
        dest: /root/docker/production-container-3