---
- hosts: 192.168.0.119
  user: root

  task:
  - name: BASIC update
    ansible.builtin.shell: sudo yum update -y

  - name: BASIC update
    yum:
      name:
        - nc
      state: latest
  
  